# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)


In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
!nvidia-smi

Tue May 30 21:41:48 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
import torch


# Create random tensor
rand_tensor = torch.rand((7,7))
rand_tensor, rand_tensor.shape


(tensor([[0.9916, 0.3270, 0.6674, 0.5466, 0.3775, 0.8793, 0.7881],
         [0.3211, 0.8463, 0.6063, 0.9726, 0.8848, 0.2871, 0.4577],
         [0.7544, 0.7924, 0.1981, 0.9442, 0.6772, 0.9754, 0.5898],
         [0.9279, 0.3948, 0.7407, 0.3972, 0.2289, 0.1623, 0.0326],
         [0.0761, 0.3088, 0.4867, 0.9744, 0.5716, 0.1332, 0.3046],
         [0.2467, 0.5974, 0.5344, 0.5366, 0.2635, 0.0532, 0.4892],
         [0.6883, 0.0932, 0.2941, 0.9909, 0.6718, 0.2343, 0.0787]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
rand_tensor_2 = torch.rand((1, 7))

# Perform matrix multiplication 

torch.mm(rand_tensor, rand_tensor_2.T)


tensor([[1.4918],
        [1.6970],
        [1.4684],
        [1.3674],
        [1.1498],
        [1.1875],
        [1.0635]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [24]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
random_tensor1 = torch.rand((7, 7))
random_tensor2 = torch.rand((1, 7))

# Matrix multiply tensors
z = torch.mm(random_tensor1, random_tensor2.T)
z, z.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [11]:
device = "cuda" if torch.cuda.is_available() else "cpc"
device
tensor_gpu = torch.rand((7, 7)).to(device)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [25]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [27]:
# Set random seed
torch.manual_seed(seed=1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
# creating tensors and then move to device generates
# different tensor values from directly generating 
# tensors by setting device 
tensor_gpu1 = torch.rand(size = (2, 3)).to(device)
print(tensor_gpu1)

tensor_gpu2 = torch.rand(size = (2, 3)).to(device)
print(tensor_gpu2)

print(torch.mm(tensor_gpu1, tensor_gpu2.T))


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')
tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
mat = torch.mm(tensor_gpu1, tensor_gpu2.T)
mat, mat.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
print(mat.max())

# Find min
print(mat.min())


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max
print(mat.argmax())



# Find arg min
print(mat.argmin())


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [31]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_rand1 = torch.rand(size=(1, 1, 1, 10))
print(tensor_rand1)


# Remove single dimensions
tensor_squeeze = torch.squeeze(tensor_rand1)


# Print out tensors and their shapes
print(tensor_squeeze)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
