In [ ]:
!pip install rapids

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.0/247.0 kB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.0/247.0 kB 30.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.0/115.0 kB 16.9 MB/s eta 0:00:00


In [ ]:
import rapids
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors
### Creating tensors

PyTorch tensors are created using `torch.Tensor()` -- https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)

# get scalar back as a Python int
print(scalar.item())

tensor(7)
0
7


In [ ]:
# Vector
vector = torch.Tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7., 7.])
1
torch.Size([2])


In [ ]:
# MATRIX
MATRIX = torch.Tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7.,  8.],
        [ 9., 10.]])
2
torch.Size([2, 2])


In [ ]:
# first dimension of MATRIX
print(MATRIX[0])

# second dimension of MATRIX
print(MATRIX[1])

tensor([7., 8.])
tensor([ 9., 10.])


In [ ]:
MATRIX[0, 1]

tensor(8.)

In [ ]:
# TENSOR
# the first dimension (out most dimension only has 1 element)
# the 2nd and 3rd dimensions have 3 elements each
TENSOR = torch.Tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])
3
torch.Size([1, 3, 3])


In [ ]:
TENSOR[0]

tensor([[1., 2., 3.],
        [3., 6., 9.],
        [2., 4., 5.]])

In [ ]:
TENSOR[0][1]

tensor([3., 6., 9.])

### using GPU on PyTorch
* set up device dependingon the availability of GPU
* create a tensor
* move tensor to GPU
* move tensor back from GPU to CPU

In [ ]:
# generate a tensor
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor.device)

# define device depending on availability of GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

tensor_gpu = tensor.to(device)
print(f'tensor = {tensor_gpu, tensor_gpu.device}')

print(f'original tensor = {tensor, tensor.device}')

cpu
cuda
tensor = (tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))
original tensor = (tensor([1, 2, 3]), device(type='cpu'))


In [ ]:
# create a copy of a tensor on GPU, and move it to CPU
tensor_cpu = tensor_gpu.cpu().numpy()
print(f'tensor_cpu = {tensor_cpu}')
print(f'tensor_gpu = {tensor_gpu}')

tensor_cpu = [1 2 3]
tensor_gpu = tensor([1, 2, 3], device='cuda:0')
